### ISSUE TITLE
Error in Generate .flo files using FlowNet2

### ISSUE THREAD

**Issue by eya-abid** [Gauravv97/flownet2-Colab#7]
Hii,
When trying to execute this command: !python main.py --inference --model FlowNet2 --save_flow --save ./output --inference_dataset ImagesFromFolder --inference_dataset_root ./frames/ --resume ./FlowNet2_checkpoint.pth.tar

I get this error: Traceback (most recent call last):
  File "main.py", line 210, in <module>
    checkpoint = torch.load(args.resume)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 545, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 4366622435430481568 got 256

I already loaded the checkpoint tar file from my drive, but now it induced another issue.

**Comment by Gauravv97** [comment]
Hi @eya-abid,

I was not able to replicate your error. Are you using the same sample video and the [model](https://drive.google.com/u/0/uc?id=1hF8vS6YeHkx3j2pfCeQqqZGwA_PJq_Da&export=download) (Don't know why the gdd download is not working for this file) mentioned in the notebook?

**Comment by gseegan** [comment]
Hi,
I am getting a similar error trying to load the tar file:

Building FlowNet2 model
  [3.495s] Effective Batch Size: 8
  [3.496s] Number of parameters: 162518834
  [3.496s] Initializing CUDA
  [6.251s] Parallelizing
  [6.253s] Loading checkpoint './FlowNet2_checkpoint.pth.tar'
  [6.253s] Operation failed

Traceback (most recent call last):
  File "main.py", line 210, in <module>
    checkpoint = torch.load(args.resume)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 528, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '<'.

The tar file downloaded from Google Drive is only about 2K.
Thanks.

**Comment by eya-abid** [comment]
I suggest putting the model tar file in the same git directory that we are cloning - Git cloning, supposedly, preserves the file as it is - Uploading and using gdd is problematic within Colab apparently.

**Comment by Gauravv97** [comment]
Hi @gseegan, there has been an issue with this file. I suggest manually downloading the file and uploading it or creating a new public link from your gdrive.

Hi @eya-abid , I think there are size limits to Git Repositories. I would try to host the file in my gdrive or give a warning to users to manually download the file.

Is your issue resolved? Was it due to video file?
